<?php
/**
 * Alxarafe. Development of PHP applications in a flash!
 * Copyright (C) 2018-2020 Alxarafe <info@alxarafe.com>
 */

namespace Alxarafe\Core\Renders\Twig\Components;

use DateTime;

/**
 * Class InputComponent
 *
 * @package Alxarafe\Core\Renders\Twig\Components
 */
class InputComponent extends AbstractComponent
{
    /**
     * Contains component type.
     *
     * @doc https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
     *
     * @var string
     */
    public $type;

    /**
     * Contains component value.
     *
     * @var string
     */
    public $value;

    /**
     * Contains component minimum value.
     *
     * @var float
     */
    public $min;

    /**
     * Contains component maximum value.
     *
     * @var float
     */
    public $max;

    /**
     * Contains component pattern for regex validation.
     *
     * @var string
     */
    public $pattern;

    /**
     * Contains component placeholder.
     *
     * @var string
     */
    public $placeholder;

    /**
     * InputComponent constructor.
     *
     * @param $parameters
     */
    public function __construct($parameters)
    {
        // TODO: Verify all fields
        switch ($parameters['type']) {
            case 'datetime':
                if (isset($parameters['value']) && $parameters['value'] != '') {
                    $dt = new DateTime($parameters['value']);
                    $parameters['value'] = $dt->format('Y-m-d\TH:i:s');
                }
                break;
            case 'checkbox':
                $parameters['value'] = $parameters['value'] == 1 ? 1 : 0;
                break;
        }

        parent::__construct($parameters);
        // TESTED: checkbox, number, datetime-local, text
        // NOT TESTED: button, color, date, email, file, hidden, image, month, password, radio, range, reset, search, submit, tel, time, url, week
    }

    public function toHtml($readOnly = false): string
    {
        /**
         * TODO: Entiendo toHtml debería de existir tanto para editar como para mostrar.
         * Lo debajo comentado, entiendo que debería de estar en la opción de mostrar,
         * de manera que muestre los datos de forma entendible por el usuario.
         *
         * Tanto la opción de listar un controlador, como en la de mostrar un registro,
         * campos del tipo fecha aparecen con la fecha mal formada YYYY-MM-DD HH:MM_SS,
         * y campos de tipo lógico aparecen con un 1 o un 0, en lugar de algo más entendible.
         *
         * Incluso en al mostrar una fecha, se muestra de la forma YYYY-MM-DDTHH:MM_SS, que
         * es la que entiende el componente de edición de timestamps.
         *
         * TODO: Otro problema está en la edición de timestamp nulos, que pone el instante actual.
         */
        switch ($this->type) {
            case 'datetime':
                // $dt = new \DateTime($this->value);
                // $this->value = $dt->format('d-m-Y H:i:s');
                break;
            case 'checkbox':
                // if ($this->value == 1) {
                //     $this->value = '<i class="fa fa-check-square" aria-hidden="true"></i>';
                // } else {
                //     $this->value = '<i class="fa fa-square" aria-hidden="true"></i>';
                // }
                break;
        }
        return parent::toHtml($readOnly); // TODO: Change the autogenerated stub
    }

    /**
     * Return the template path to render this component.
     *
     * @return string
     */
    public function getTemplatePath(): string
    {
        return '@Core/components/input.html';
    }
}
