<?php

namespace Alxarafe\Test\Core\Helpers\Utils;

use Alxarafe\Core\Helpers\Utils\TextUtils;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-05 at 15:29:42.
 */
class TextUtilsTest extends TestCase
{
    /**
     * @var TextUtils
     */
    protected $object;

    public function __construct()
    {
        parent::__construct();
        $this->object = new TextUtils;
    }

    /**
     * @use TextUtils::camelToSnake
     */
    public function testCamelToSnake(): void
    {
        $testCamelCase = 'CamelCase';
        $testSnakeCase = 'camel_case';
        $this->assertSame($this->object::camelToSnake($testCamelCase), $testSnakeCase);
    }

    /**
     * @use TextUtils::snakeToCamel
     */
    public function testSnakeToCamel(): void
    {
        $testSnakeCase = 'camel_case';
        $testCamelCase = 'CamelCase';
        $this->assertSame($this->object::snakeToCamel($testSnakeCase), $testCamelCase);
    }

    /**
     * @use TextUtils::randomString
     */
    public function testRandomString(): void
    {
        $this->assertNotEmpty($this->object::randomString());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        $this->object = null;
    }
}
