sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

env:
    - DB=mysql

install:
    # https://docs.travis-ci.com/user/languages/php/#apache--php
    # https://github.com/mitchellkrogza/Travis-CI-for-Apache-For-Testing-Apache-and-PHP-Configurations/blob/master/travisCI/install-apache.sh
    # Update and install base system
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2
    # Add PHP 7.2 Repository and install PHP 7.2
    - sudo add-apt-repository -y ppa:ondrej/php
    - sudo apt-get update
    - sudo apt-get install -y --force-yes php7.2 php7.2-common php7.2-cli php7.2-fpm libapache2-mod-php7.2
    - sudo a2enmod php7.2
    # Configure apache virtual hosts
    - sudo cp -f config/build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # Enable mod rewrite module
    - sudo a2enmod rewrite
    - sudo a2enmod expires
    # Set ServerName Globally
    - echo "ServerName local.dev" | sudo tee /etc/apache2/conf-available/fqcn.conf
    - sudo a2enconf fqcn
    - echo "127.0.0.1 local.dev" | sudo tee -a /etc/hosts
    # Restart services
    - sudo service apache2 restart
    - sudo service php7.2-fpm restart
    - travis_retry composer install --no-interaction --prefer-source

services:
    - memcached
    - mysql

addons:
    mariadb: '10.0'
    hosts:
        - local.dev

before_install:
    - npm i -g npm
    - npm i -g bower
    - bower install

before_script:
    # Create database
    - mysql -e 'DROP DATABASE IF EXISTS alxarafe;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS alxarafe;'
    # Copy default config.yaml
    - cp config/config-travis.yaml config/config.yaml
    # Do a lookup on local.dev hostname set above
    - nslookup local.dev
    # Do an Apache Config Test
    - sudo apache2ctl configtest
    # Check if the site responds OK
    - curl -vsf 'http://local.dev/index.php' &> /dev/stdout

script:
    # Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
    - vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHP-CS.
    - vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHPUnit test.
    - vendor/bin/phpunit --configuration phpunit.xml

matrix:
    include:
        -   php: hhvm
            dist: trusty
    allow_failures:
        -   php: hhvm
        -   php: nightly
    fast_finish: true

after_failure:
    - sudo cat $TRAVIS_BUILD_DIR/apache-error.log
#notifications:
#    email:
#        - hello@withknown.com