sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

env:
    - DB=mysql

install: travis_retry composer install --no-interaction --prefer-source

services:
    - memcached
    - mysql

addons:
    mariadb: '10.0'

before_install:
    - npm i -g npm
    - npm i -g bower
    - bower install

before_script:
    # https://docs.travis-ci.com/user/languages/php/#apache--php
    # https://www.marcus-povey.co.uk/2016/02/16/travisci-with-php-7-on-apache-php-fpm/
    # Update and install base system
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-fastcgi
    - sudo apt-get install -y --force-yes php7*
    # Enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
    - sudo chown -R travis:travis /var/lib/apache2/fastcgi
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - sudo cp config/build/travis-www.conf.php ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.php
    # Configure apache virtual hosts
    - sudo cp -f config/build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    # Restart services
    - sudo service apache2 restart
    - mysql -e 'DROP DATABASE IF EXISTS alxarafe;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS alxarafe;'
    - cp config/config-travis.yaml config/config.yaml

script:
    # Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
    - vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHP-CS.
    - vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHPUnit test.
    - vendor/bin/phpunit --configuration phpunit.xml
matrix:
    include:
        -   php: hhvm
            dist: trusty
    allow_failures:
        -   php: hhvm
        -   php: nightly
    fast_finish: true
after_failure:
    - sudo cat $TRAVIS_BUILD_DIR/apache-error.log
#notifications:
#    email:
#        - hello@withknown.com