sudo: false
language: php

php:
    - 7.1
    - 7.2
    - nightly

env:
    - DB=mysql

install: travis_retry composer install --no-interaction --prefer-source

services:
    - memcached
    - mysql

addons:
    mariadb: '10.0'

before_install:
    - npm i -g npm
    - npm i -g bower
    - bower install

before_script:
    - curl http://ipinfo.io/ip
    # https://docs.travis-ci.com/user/languages/php/#apache--php
    # https://github.com/mitchellkrogza/Travis-CI-for-Apache-For-Testing-Apache-and-PHP-Configurations/blob/master/travisCI/install-apache.sh
    # Update and install base system
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2
    # Add PHP 7.2 Repository
    - sudo add-apt-repository -y ppa:ondrej/php
    # Install PHP 7.2
    - sudo apt-get update
    - sudo apt-get install -y --force-yes php7.2 php7.2-common php7.2-cli php7.2-fpm libapache2-mod-php7.2
    - sudo a2enmod php7.2
    # Configure apache virtual hosts
    - sudo cp -f config/build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    # Enable mod rewrite module
    - sudo a2enmod rewrite
    - sudo a2enmod expires
    # Set ServerName Globally
    - sudo cp config/build/travis-ci-servername /etc/apache2/conf-available/servername.conf
    - sudo a2enconf servername
    # Restart services
    - sudo service apache2 restart
    # Restart PHP
    - sudo service php7.2-fpm restart
    # Create database
    - mysql -e 'DROP DATABASE IF EXISTS alxarafe;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS alxarafe;'
    # Copy default config.yaml
    - cp config/config-travis.yaml config/config.yaml

script:
    # Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
    - vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHP-CS.
    - vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHPUnit test.
    - vendor/bin/phpunit --configuration phpunit.xml

matrix:
    include:
        -   php: hhvm
            dist: trusty
    allow_failures:
        -   php: hhvm
        -   php: nightly
    fast_finish: true

after_failure:
    - sudo cat $TRAVIS_BUILD_DIR/apache-error.log
#notifications:
#    email:
#        - hello@withknown.com