dist: xenial
sudo: required
language: php

addons:
    mariadb: '10.0'
    hosts:
        - localhost
    apt:
        packages:
            - apache2
            - postfix
            - libapache2-mod-fastcgi

services:
    - memcached
    - mysql

php:
    - 7.1
    - 7.2

env:
    global:
        - VHOST_URL=localhost

before_install:
    - npm i -g npm
    - npm i -g bower
    - bower install
    # Fix travis error https://github.com/travis-ci/travis-ci/issues/8607
    - sudo rm -vf /etc/apt/sources.list.d/*riak*
    # Apache & php-fpm configuration
    - bash config/build/travis/setup-php-fpm.sh
    - bash config/build/travis/setup-apache.sh
    # Permissions
    - sudo chown -R www-data:www-data $TRAVIS_BUILD_DIR
    - sudo chown -R 775 $TRAVIS_BUILD_DIR
    - sudo chmod +x /home/travis/build
    - sudo service apache2 restart

install:
    - travis_retry composer install --no-interaction --prefer-source

before_script:
    # Create database
    - mysql -e 'DROP DATABASE IF EXISTS alxarafe;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS alxarafe;'
    # Copy default config.yaml
    - cp config/config-travis.yaml config/config.yaml

script:
    # Run PHP-CS Beautifier and Fixer: to format some common non PSR code that can be auto-fixed.
    - vendor/bin/phpcbf --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHP-CS.
    - vendor/bin/phpcs --tab-width=4 --encoding=utf-8 --standard=phpcs.xml src/Alxarafe/Core -s
    # Run PHPUnit test.
    - vendor/bin/phpunit --coverage-clover=reports/coverage.xml

matrix:
    fast_finish: true

after_failure:
    - sudo cat $TRAVIS_BUILD_DIR/apache-error.log
#notifications:
#    email:
#        - hello@withknown.com