Search.appendIndex(
    [
                {
            "fqsen": "\\Modules\\Agenda\\Api\\PersonApiController",
            "name": "PersonApiController",
            "summary": "Class\u0020PersonApiController.",
            "url": "classes/Modules-Agenda-Api-PersonApiController.html"
        },                {
            "fqsen": "\\Modules\\Agenda\\Api\\PersonApiController\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieve\u0020a\u0020Person\u0020by\u0020ID.",
            "url": "classes/Modules-Agenda-Api-PersonApiController.html#method_get"
        },                {
            "fqsen": "\\CoreModules\\Admin\\Api\\LoginController",
            "name": "LoginController",
            "summary": "",
            "url": "classes/CoreModules-Admin-Api-LoginController.html"
        },                {
            "fqsen": "\\CoreModules\\Admin\\Api\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CoreModules-Admin-Api-LoginController.html#method___construct"
        },                {
            "fqsen": "\\CoreModules\\Admin\\Api\\UserApiController",
            "name": "UserApiController",
            "summary": "Class\u0020UserApiController.",
            "url": "classes/CoreModules-Admin-Api-UserApiController.html"
        },                {
            "fqsen": "\\CoreModules\\Admin\\Api\\UserApiController\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Retrieve\u0020User\u0020details\u0020by\u0020ID.",
            "url": "classes/CoreModules-Admin-Api-UserApiController.html#method_get"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Modules\\Agenda\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/modules-agenda-api.html"
        },                {
            "fqsen": "\\Modules\\Agenda",
            "name": "Agenda",
            "summary": "",
            "url": "namespaces/modules-agenda.html"
        },                {
            "fqsen": "\\Modules",
            "name": "Modules",
            "summary": "",
            "url": "namespaces/modules.html"
        },                {
            "fqsen": "\\CoreModules\\Admin\\Api",
            "name": "Api",
            "summary": "",
            "url": "namespaces/coremodules-admin-api.html"
        },                {
            "fqsen": "\\CoreModules\\Admin",
            "name": "Admin",
            "summary": "",
            "url": "namespaces/coremodules-admin.html"
        },                {
            "fqsen": "\\CoreModules",
            "name": "CoreModules",
            "summary": "",
            "url": "namespaces/coremodules.html"
        }            ]
);
