<?php

namespace Alxarafe\Test\Core\Helpers;

use Alxarafe\Core\Helpers\FormatUtils;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-03-05 at 15:25:12.
 */
class FormatUtilsTest extends TestCase
{
    /**
     * @var FormatUtils
     */
    protected $object;

    /**
     * @use FormatUtils::getFormatDate
     */
    public function testGetFormatDate()
    {
        $this->assertNotEmpty($this->object::getFormatDate());
    }

    /**
     * @use FormatUtils::getFormatDateTime
     */
    public function testGetFormatDateTime()
    {
        $this->assertNotEmpty($this->object::getFormatDateTime());
    }

    /**
     * @use FormatUtils::getFormatTime
     */
    public function testGetFormatTime()
    {
        $this->assertNotEmpty($this->object::getFormatTime());
    }

    /**
     * @use FormatUtils::getFormattedDate
     */
    public function testGetFormattedDate()
    {
        $this->assertNotEmpty($this->object::getFormattedDate());
    }

    /**
     * @use FormatUtils::getFormatted
     */
    public function testGetFormatted()
    {
        $this->assertNotEmpty($this->object::getFormatted($this->object::getFormatDate()));
        $this->assertNotEmpty($this->object::getFormatted($this->object::getFormatDateTime()));
        $this->assertNotEmpty($this->object::getFormatted($this->object::getFormatTime()));
    }

    /**
     * @use FormatUtils::getFormattedTime
     */
    public function testGetFormattedTime()
    {
        $this->assertNotEmpty($this->object::getFormattedTime());
    }

    /**
     * @use FormatUtils::getFormattedDateTime
     */
    public function testGetFormattedDateTime()
    {
        $this->assertNotEmpty($this->object::getFormattedDateTime());
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FormatUtils();
        $this->object::loadConfig();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->object = null;
    }
}
