<?php
/**
 * Alxarafe. Development of PHP applications in a flash!
 * Copyright (C) 2018-2020 Alxarafe <info@alxarafe.com>
 */

namespace Alxarafe\Core\Database\Fields;

use Alxarafe\Core\Providers\Translator;

class IntegerField extends AbstractNumericField
{
    /**
     * AbstractNumericComponent constructor.
     *
     * @param $parameters
     */
    public function __construct()
    {
        parent::__construct();

        $this->addRequiredFields(['autoincrement']);
    }

    public function assignData(array $data)
    {
        parent::assignData($data); // TODO: Change the autogenerated stub

        $bits = 8 * $this->length;
        $total = 2 ** $bits;

        $unsigned = $this->unsigned === 'yes';
        if ($unsigned) {
            $min = 0;
            $max = $total - 1;
        } else {
            $min = -$total / 2;
            $max = $total / 2 - 1;
        }

        if ($this->min === null) {
            $this->min = $min;
        }

        if ($this->max === null) {
            $this->max = $max;
        }
    }

    public static function test($key, $struct, &$value)
    {
        $trans = Translator::getInstance();
        $params = ['%field%' => $trans->trans($key), '%value%' => $value];

        $unsigned = isset($struct['unsigned']) && $struct['unsigned'] === 'yes';
        $min = $struct['min'] ?? null;
        $max = $struct['max'] ?? null;
        if ($unsigned && $value < 0) {
            self::$errors[] = $trans->trans('error-negative-unsigned', $params);
        }
        if (isset($min) && $value < $min) {
            $params['%min%'] = $min;
            self::$errors[] = $trans->trans('error-less-than-minimum', $params);
        }
        if (isset($max) && $value > $max) {
            $params['%max%'] = $max;
            self::$errors[] = $trans->trans('error-greater-than-maximum', $params);
        }

        return (count(self::$errors) === 0);
    }
}
