<?php
/**
 * Alxarafe. Development of PHP applications in a flash!
 * Copyright (C) 2018-2020 Alxarafe <info@alxarafe.com>
 */

namespace Alxarafe\Core\Database\Fields;

class IntegerField extends AbstractNumericField
{
    /**
     * AbstractNumericComponent constructor.
     *
     * @param $parameters
     */
    public function __construct()
    {
        parent::__construct();

        $this->addRequiredFields(['autoincrement']);
    }

    public function assignData(array $data)
    {
        parent::assignData($data); // TODO: Change the autogenerated stub

        $bits = 8 * $this->length;
        $total = 2 ** $bits;

        $unsigned = $this->unsigned === 'yes';
        if ($unsigned) {
            $min = 0;
            $max = $total - 1;
        } else {
            $min = -$total / 2;
            $max = $total / 2 - 1;
        }

        if ($this->min === null) {
            $this->min = $min;
        }

        if ($this->max === null) {
            $this->max = $max;
        }
    }

    /**
     * TODO IMPORTANT! We have to check that the test method is correct for this field.
     *
     * The passed value is verified to meet the necessary requirements for the field.
     * The field name is needed in case you have to show a message, to be able to
     * report what field it is.
     * The value of the field may be returned modified if the test can correct it.
     * Returns true if the value is valid.
     *
     * @param $key
     * @param $value
     *
     * @return bool
     */
    public function test($key, &$value): bool
    {
        $params = ['%field%' => $this->trans->trans($key), '%value%' => $value];

        $unsigned = $this->unsigned === 'yes';
        $min = $this->min ?? null;
        $max = $this->max ?? null;
        if ($unsigned && $value < 0) {
            self::$errors[] = $this->trans->trans('error-negative-unsigned', $params);
        }
        if (isset($min) && $value < $min) {
            $params['%min%'] = $min;
            self::$errors[] = $this->trans->trans('error-less-than-minimum', $params);
        }
        if (isset($max) && $value > $max) {
            $params['%max%'] = $max;
            self::$errors[] = $this->trans->trans('error-greater-than-maximum', $params);
        }

        return (count(self::$errors) === 0);
    }
}
